#!/usr/bin/env python3
"""
assemble_figures.py — Composite figure assembly for TBME paper.

Loads individual panel PNGs generated by plot_*.py scripts and assembles
them into multi-panel composite PDFs/PNGs ready for LaTeX inclusion.

TBME style:
  - Double-column (full-width): 7.0 in
  - Single-column: 3.5 in
  - Panel labels: (a)(b)... upper-left inside each panel, 7 pt serif
  - DPI: 300

Usage:
  # Build all figures:
  python scripts/assemble_figures.py --all \
      --figures-dir results/figures/phase0_v3 \
      --out-dir results/figures/assembled

  # Build one figure:
  python scripts/assemble_figures.py --fig fig1 \
      --figures-dir results/figures/phase0_v3 \
      --out-dir results/figures/assembled

Available --fig values:
  fig1          Fig 1   — Saturation (main tasks)
  fig1_sec      S-Fig   — Saturation (secondary tasks: OSA + depression)

  fig2_kvsk     Fig 2a  — AUROC vs K  (main tasks, iso-compute)
  fig2_heatmap  Fig 2b  — Heatmap     (main tasks, iso-compute)
  fig2_mincost  Fig 2c  — Min-cost    (main tasks, iso-compute)
  sfig_iso_kvsk     Supplementary — AUROC vs K  (secondary tasks)
  sfig_iso_heatmap  Supplementary — Heatmap     (secondary tasks)
  sfig_iso_mincost  Supplementary — Min-cost    (secondary tasks)

  fig3          Fig 3   — Task Landscape (6A scatter + 6C lollipop)

  sfig1         S-Fig 1 — K-Aggregation Curves  (main tasks, test_window_sweep)
  sfig1_sec     S-Fig   — K-Aggregation Curves  (secondary tasks)
  sfig3         S-Fig 3 — Iso-Compute Full: metric_vs_total+pareto+marginal (sex+apnea)
  sfig4a        S-Fig 4a — ECE vs Context       (6 tasks, 2B multi-head)
  sfig4b        S-Fig 4b — Reliability Diagrams (3 tasks, 2A)
  sfig5         S-Fig 5  — Cross-Cohort Saturation (3 tasks)
  sfig6a        S-Fig 6a — Variance Violins      (3 tasks)
  sfig6b        S-Fig 6b — Hard-Subject Bars     (main tasks)
  sfig6b_sec    S-Fig    — Hard-Subject Bars     (secondary tasks)
  sfig7         S-Fig 7  — Window Position       (sleep_eff + sex, 2×2)
  sfig8         S-Fig 8  — Compute Scaling 1B   (main tasks)
  sfig8_sec     S-Fig    — Compute Scaling 1B   (secondary tasks)
  sfig9         S-Fig 9  — K* Histograms        (main tasks)
  sfig9_sec     S-Fig    — K* Histograms        (secondary tasks)
  sfig10a       S-Fig 10a — PR Curves 8A        (binary main tasks)
  sfig10b       S-Fig 10b — AUC-PR vs Context   (binary main tasks)
  sfig11        S-Fig 11 — U-Shape Training 1A  (main tasks)
  sfig11_sec    S-Fig    — U-Shape Training 1A  (secondary tasks)

  all           Build all of the above

Note: Fig 4, S-Fig 2, S-Fig 12 are pre-assembled by their generating scripts —
      no assembly needed.
"""

import argparse
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib.gridspec as gridspec
import numpy as np

# ── TBME constants ─────────────────────────────────────────────────────────────
FULL_WIDTH = 7.0    # inches, double-column
HALF_WIDTH = 3.5    # inches, single-column
DPI        = 300
ROW_H      = 2.2    # default row height (inches) per panel row

# Panel label: placed centred below each panel
LABEL_SIZE = 5          # pt — kept small relative to source PNG text (9–10 pt)
LABEL_X    = 0.5        # centred horizontally
LABEL_Y    = -0.03      # just below the bottom edge of the axis (negative = outside)
LABEL_FONT = "serif"

# Inter-panel spacing (fraction of average axes size).
# Must be large enough that LABEL_Y text (at -0.03 axes units below the bottom)
# does not get covered by the row below.  clip_on=False on the text prevents
# axis-level clipping; HSPACE prevents figure-level overlap.
HSPACE = 0.14           # vertical gap between rows
WSPACE = 0.04           # horizontal gap between columns

# ── Task definitions ───────────────────────────────────────────────────────────
# Main tasks: strong results, included in main paper figures
MAIN_TASKS = [
    "sex_binary",
    "age_class",
    "apnea_binary",
    "bmi_binary",
    "sleep_efficiency_binary",
]

# Secondary tasks: small N or erratic results → supplementary only
SECONDARY_TASKS = [
    "osa_binary_apples_postqc",
    "depression_extreme_binary",
]

ALL_TASKS = MAIN_TASKS + SECONDARY_TASKS

# Tasks that have PR curves (binary classification only; age_class is 3-class)
BINARY_MAIN   = [t for t in MAIN_TASKS      if t != "age_class"]
BINARY_SECOND = [t for t in SECONDARY_TASKS if t != "age_class"]

# Tasks for ECE calibration (S-Fig 4a): all main + OSA; exclude depression
CALIBRATION_TASKS = MAIN_TASKS + ["osa_binary_apples_postqc"]

# Task display names — match paper tables exactly
TASK_LABEL = {
    "sex_binary":                  "Sex classification",
    "age_class":                   "Age group",
    "apnea_binary":                "Sleep apnea (AHI≥15)",
    "bmi_binary":                  "BMI (obese)",
    "sleep_efficiency_binary":     "Sleep efficiency",
    "depression_extreme_binary":   "Depression (extreme)",
    "osa_binary_apples_postqc":    "OSA (APPLES)",
}

# Short label for tight figures (e.g. when axis is narrow)
TASK_SHORT = {
    "sex_binary":                  "Sex",
    "age_class":                   "Age group",
    "apnea_binary":                "Apnea (AHI≥15)",
    "bmi_binary":                  "BMI",
    "sleep_efficiency_binary":     "Sleep efficiency",
    "depression_extreme_binary":   "Depression",
    "osa_binary_apples_postqc":    "OSA (APPLES)",
}


# ── Image helpers ──────────────────────────────────────────────────────────────

def load_img(path: Path):
    """Load PNG; return None with a warning if missing."""
    if not path.exists():
        print(f"  [WARN] missing: {path}", file=sys.stderr)
        return None
    return mpimg.imread(str(path))


def img_aspect(path: Path) -> float:
    """Return width/height pixel ratio of a PNG, or 1.5 if unreadable."""
    if not path.exists():
        return 1.5
    try:
        img = mpimg.imread(str(path))
        h, w = img.shape[:2]
        return w / h
    except Exception:
        return 1.5


def show_img(ax, img, label=None):
    """Show image in axis preserving its natural aspect ratio.
    Label is drawn inside upper-left with a white backing box.
    """
    if img is None:
        ax.set_facecolor("#ebebeb")
        ax.text(0.5, 0.5, "MISSING", ha="center", va="center",
                transform=ax.transAxes, color="#cc0000", fontsize=7,
                fontfamily=LABEL_FONT)
        ax.set_xticks([]); ax.set_yticks([])
    else:
        # aspect='equal' (imshow default) preserves image proportions — no squishing.
        ax.imshow(img, interpolation="lanczos")
        ax.axis("off")

    if label:
        ax.text(LABEL_X, LABEL_Y, label,
                ha="center", va="top", transform=ax.transAxes,
                fontsize=LABEL_SIZE, fontfamily=LABEL_FONT,
                clip_on=False)   # prevent axes boundary from clipping outside-axis text


# ── Grid builders ──────────────────────────────────────────────────────────────

def make_grid(n_panels: int, n_cols: int, figsize: tuple) -> tuple:
    """
    Standard uniform grid. Excess cells at the end are hidden.
    Returns (fig, axes_flat) where len == n_panels.
    Spacing is set via subplots_adjust — NOT tight_layout, which incorrectly
    inflates inter-row gaps when axes have below-axis text labels.
    """
    n_rows = (n_panels + n_cols - 1) // n_cols
    fig, axes = plt.subplots(n_rows, n_cols, figsize=figsize)
    flat = np.array(axes).ravel() if n_rows * n_cols > 1 else [axes]
    for ax in flat[n_panels:]:
        ax.set_visible(False)
    fig.subplots_adjust(hspace=HSPACE, wspace=WSPACE)
    return fig, flat[:n_panels]


def make_grid_centered(n_panels: int, n_cols: int, figsize: tuple) -> tuple:
    """
    Like make_grid but the last (incomplete) row is horizontally centred.
    Uses a 2×n_cols virtual GridSpec so the offset is exact.
    """
    n_last = n_panels % n_cols
    if n_last == 0:
        return make_grid(n_panels, n_cols, figsize)

    n_rows = (n_panels + n_cols - 1) // n_cols
    vcols  = n_cols * 2          # virtual columns for half-column centering

    fig = plt.figure(figsize=figsize)
    gs  = gridspec.GridSpec(n_rows, vcols, figure=fig,
                             hspace=HSPACE, wspace=WSPACE)

    axes_flat = []
    for row in range(n_rows - 1):
        for col in range(n_cols):
            axes_flat.append(fig.add_subplot(gs[row, col * 2 : col * 2 + 2]))

    # Centre n_last panels in the last row
    offset = n_cols - n_last
    for col in range(n_last):
        start = offset + col * 2
        axes_flat.append(fig.add_subplot(gs[n_rows - 1, start : start + 2]))

    return fig, axes_flat


def save_fig(fig, out_dir: Path, stem: str):
    """Save as PDF and PNG. bbox_inches='tight' trims outer whitespace."""
    out_dir.mkdir(parents=True, exist_ok=True)
    for ext in ("pdf", "png"):
        p = out_dir / f"{stem}.{ext}"
        fig.savefig(str(p), dpi=DPI, bbox_inches="tight")
        print(f"  saved → {p}")
    plt.close(fig)


# ── Figsize helpers ─────────────────────────────────────────────────────────────

def fs(n_rows: int, sample_path: Path = None,
       n_cols: int = 3, width: float = FULL_WIDTH,
       row_h: float = None) -> tuple:
    """
    Compute figsize = (width, n_rows * row_h).

    row_h is derived from the source image's aspect ratio when sample_path
    is given — this ensures no squishing.  If sample_path is missing or
    row_h is given explicitly, that value is used directly.

    col_width = width / n_cols
    row_h     = col_width / (img_w / img_h)      # natural height for that width
    """
    if row_h is None:
        aspect = img_aspect(sample_path) if sample_path else 1.5
        col_w  = width / n_cols
        row_h  = col_w / aspect
        # floor: 0.8 in minimum so panels are never invisible; aspect ratio drives height
        row_h  = max(row_h, 0.8)
    return (width, n_rows * row_h)


# ── Figure builders ─────────────────────────────────────────────────────────────

# ── Fig 1 variants ─────────────────────────────────────────────────────────────

def _build_saturation(tasks, fdir, out_dir, stem):
    """Generic saturation assembler for any task list."""
    n = len(tasks)
    n_cols = 3
    sample = fdir / "saturation" / f"saturation_{tasks[0]}_auroc_test.png"
    n_rows = (n + n_cols - 1) // n_cols
    fig, axes = make_grid_centered(n, n_cols, fs(n_rows, sample, n_cols))
    for i, (ax, task) in enumerate(zip(axes, tasks)):
        p = fdir / "saturation" / f"saturation_{task}_auroc_test.png"
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, stem)


def build_fig1(fdir, out_dir):
    """Fig 1 — Context Saturation, main tasks (2×3 layout, 5 panels)."""
    print("Building Fig 1 — Saturation (main) …")
    _build_saturation(MAIN_TASKS, fdir, out_dir, "fig1_saturation_main")


def build_fig1_sec(fdir, out_dir):
    """S-Fig — Saturation, secondary tasks (1×2)."""
    print("Building Fig 1 secondary — Saturation (OSA + depression) …")
    _build_saturation(SECONDARY_TASKS, fdir, out_dir, "sfig_saturation_secondary")


# ── Fig 2 iso-compute variants ──────────────────────────────────────────────────

ISO_PANELS = {
    "kvsk":    ("metric_vs_k_auroc.png",       "AUROC vs K"),
    "heatmap": ("heatmap_auroc.png",            "Iso-compute heatmap"),
    "mincost": ("min_cost_frontier_auroc.png",  "Min-cost frontier"),
    "vstotal": ("metric_vs_total_auroc.png",    "AUROC vs total context"),
    "pareto":  ("pareto_front_auroc.png",       "Pareto front"),
    "marginal":("marginal_gain_auroc.png",      "Marginal gain"),
}

def _build_iso(tasks, panel_key, head, fdir, out_dir, stem):
    """Assembler for one iso-compute panel type across multiple tasks."""
    fname, _ = ISO_PANELS[panel_key]
    n = len(tasks)
    n_cols = 3
    sample = fdir / f"{tasks[0]}_{head}" / "auroc_test" / fname
    n_rows = (n + n_cols - 1) // n_cols
    fig, axes = make_grid_centered(n, n_cols, fs(n_rows, sample, n_cols))
    for i, (ax, task) in enumerate(zip(axes, tasks)):
        p = fdir / f"{task}_{head}" / "auroc_test" / fname
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, stem)


def build_fig2_kvsk(fdir, out_dir):
    print("Building Fig 2a — AUROC vs K, main tasks …")
    _build_iso(MAIN_TASKS, "kvsk", "transformer", fdir, out_dir, "fig2a_kvsk_main")

def build_fig2_heatmap(fdir, out_dir):
    print("Building Fig 2b — Heatmap, main tasks …")
    _build_iso(MAIN_TASKS, "heatmap", "transformer", fdir, out_dir, "fig2b_heatmap_main")

def build_fig2_mincost(fdir, out_dir):
    print("Building Fig 2c — Min-cost frontier, main tasks …")
    _build_iso(MAIN_TASKS, "mincost", "transformer", fdir, out_dir, "fig2c_mincost_main")

def build_sfig_iso_kvsk_sec(fdir, out_dir):
    print("Building S-Fig — AUROC vs K, secondary tasks …")
    _build_iso(SECONDARY_TASKS, "kvsk", "transformer", fdir, out_dir, "sfig_iso_kvsk_secondary")

def build_sfig_iso_heatmap_sec(fdir, out_dir):
    print("Building S-Fig — Heatmap, secondary tasks …")
    _build_iso(SECONDARY_TASKS, "heatmap", "transformer", fdir, out_dir, "sfig_iso_heatmap_secondary")

def build_sfig_iso_mincost_sec(fdir, out_dir):
    print("Building S-Fig — Min-cost, secondary tasks …")
    _build_iso(SECONDARY_TASKS, "mincost", "transformer", fdir, out_dir, "sfig_iso_mincost_secondary")


# ── Fig 3 ───────────────────────────────────────────────────────────────────────

def build_fig3(fdir, out_dir):
    """Fig 3 — Task Landscape (6A scatter + 6C lollipop)."""
    print("Building Fig 3 — Task Landscape …")
    tc = fdir / "task_comparison"
    panels = [
        (tc / "task_comparison_6A_scatter.png", "(a) Task difficulty vs context sensitivity"),
        (tc / "task_comparison_6C_lstar.png",   "(b) Saturation context L*"),
    ]
    sample = panels[0][0]
    fig, axes = make_grid(2, 2, fs(1, sample, 2))
    for ax, (p, lbl) in zip(axes, panels):
        show_img(ax, load_img(p), lbl)
    save_fig(fig, out_dir, "fig3_task_landscape")


# ── S-Fig 1 — K-Aggregation (test_window_sweep) ────────────────────────────────

def _sweep_path(fdir: Path, task: str, head: str) -> Path:
    """Return the test_window_sweep_auroc.png path, checking the style1 archive
    first (local), then the current figures dir (cluster after regeneration),
    then metric_vs_k_auroc.png as a last fallback.

    Archive layout: results/figures_style1_archive_20260701/phase0_v3/{task}_{head}/
    Current layout: results/figures/phase0_v3/{task}_{head}/
    """
    fname = f"{task}_{head}_test_window_sweep_auroc.png"
    # 1. Archive: sibling of the "figures" parent dir
    archive = fdir.parent.parent / "figures_style1_archive_20260701" / fdir.name
    p_archive = archive / f"{task}_{head}" / fname
    if p_archive.exists():
        return p_archive
    # 2. Current figures dir (regenerated with TBME style on cluster)
    p_current = fdir / f"{task}_{head}" / fname
    if p_current.exists():
        return p_current
    # 3. Fallback: metric_vs_k from iso-compute (same content, mean_prob only)
    return fdir / f"{task}_{head}" / "auroc_test" / "metric_vs_k_auroc.png"


def _build_sfig2(tasks, fdir, out_dir, stem):
    """S-Fig 2 — K-Aggregation Curves (test_window_sweep style: mean_prob + segment-level).
    Prefers figures_style1_archive_20260701 if present; falls back to metric_vs_k.
    """
    n = len(tasks)
    n_cols = 3
    sample = _sweep_path(fdir, tasks[0], "transformer")
    n_rows = (n + n_cols - 1) // n_cols
    fig, axes = make_grid_centered(n, n_cols, fs(n_rows, sample, n_cols))
    for i, (ax, task) in enumerate(zip(axes, tasks)):
        p = _sweep_path(fdir, task, "transformer")
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, stem)

def build_sfig2(fdir, out_dir):
    print("Building S-Fig 2 — K-Aggregation Curves, main tasks …")
    _build_sfig2(MAIN_TASKS, fdir, out_dir, "sfig2_k_aggregation_main")

def build_sfig2_sec(fdir, out_dir):
    print("Building S-Fig 2 secondary — K-Aggregation Curves, secondary tasks …")
    _build_sfig2(SECONDARY_TASKS, fdir, out_dir, "sfig2_k_aggregation_secondary")


# ── S-Fig 3 — Iso-Compute Full (sex + apnea, 3 panels) ─────────────────────────

def build_sfig3_main(fdir, out_dir):
    """Main paper — iso-compute: metric_vs_total + pareto_front for sex+apnea (2×2)."""
    print("Building S-Fig 3 main — Iso-Compute (vstotal + pareto, sex+apnea) …")
    TASKS  = ["sex_binary", "apnea_binary"]
    PANELS = ["vstotal", "pareto"]
    sample = fdir / f"{TASKS[0]}_transformer" / "auroc_test" / ISO_PANELS["vstotal"][0]
    fig, axes = make_grid(4, 2, fs(2, sample, 2))
    idx = 0
    for task in TASKS:
        for pk in PANELS:
            fname, _ = ISO_PANELS[pk]
            p = fdir / f"{task}_transformer" / "auroc_test" / fname
            show_img(axes[idx], load_img(p), f"({chr(97+idx)}) {TASK_SHORT[task]}")
            idx += 1
    save_fig(fig, out_dir, "sfig3_iso_main")


def build_sfig3_marginal(fdir, out_dir):
    """S-Fig 3 supplementary — marginal gain for sex+apnea (1×2)."""
    print("Building S-Fig 3 marginal — Iso-Compute marginal gain …")
    TASKS  = ["sex_binary", "apnea_binary"]
    fname, _ = ISO_PANELS["marginal"]
    sample = fdir / f"{TASKS[0]}_transformer" / "auroc_test" / fname
    fig, axes = make_grid(2, 2, fs(1, sample, 2))
    for i, (ax, task) in enumerate(zip(axes, TASKS)):
        p = fdir / f"{task}_transformer" / "auroc_test" / fname
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, "sfig3_iso_marginal")


# ── S-Fig 4a — ECE vs Context (multi-head 2B) ──────────────────────────────────

def build_sfig4a(fdir, out_dir):
    """S-Fig 4a — ECE vs Context, 6 tasks (2×3), LSTM multi-head 2B."""
    print("Building S-Fig 4a — ECE vs Context …")
    tasks  = CALIBRATION_TASKS
    n_cols = 3
    n_rows = (len(tasks) + n_cols - 1) // n_cols
    sample = fdir / f"{tasks[0]}_lstm" / f"{tasks[0]}_calibration_2B_ece_vs_context.png"
    fig, axes = make_grid_centered(len(tasks), n_cols, fs(n_rows, sample, n_cols))
    for i, (ax, task) in enumerate(zip(axes, tasks)):
        p = fdir / f"{task}_lstm" / f"{task}_calibration_2B_ece_vs_context.png"
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, "sfig4a_ece_vs_context")


# ── S-Fig 4b — Reliability Diagrams (2A) ───────────────────────────────────────

def build_sfig4b(fdir, out_dir):
    """S-Fig 4b — Reliability Diagrams at 240m: apnea, sleep_eff, sex (1×3)."""
    print("Building S-Fig 4b — Reliability Diagrams …")
    tasks  = ["apnea_binary", "sleep_efficiency_binary", "sex_binary"]
    sample = fdir / f"{tasks[0]}_lstm" / f"{tasks[0]}_lstm_calibration_2A_reliability.png"
    fig, axes = make_grid(3, 3, fs(1, sample, 3))
    for i, (ax, task) in enumerate(zip(axes, tasks)):
        p = fdir / f"{task}_lstm" / f"{task}_lstm_calibration_2A_reliability.png"
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, "sfig4b_reliability")


# ── S-Fig 5 — Cross-Cohort Saturation ──────────────────────────────────────────

def build_sfig5(fdir, out_dir):
    """S-Fig 5 — Cross-Cohort Saturation: apnea, sleep_eff, sex (1×3)."""
    print("Building S-Fig 5 — Cross-Cohort Saturation …")
    tasks  = ["apnea_binary", "sleep_efficiency_binary", "sex_binary"]
    sample = fdir / f"{tasks[0]}_lstm" / f"{tasks[0]}_lstm_cohort_saturation_7A.png"
    fig, axes = make_grid(3, 3, fs(1, sample, 3))
    for i, (ax, task) in enumerate(zip(axes, tasks)):
        p = fdir / f"{task}_lstm" / f"{task}_lstm_cohort_saturation_7A.png"
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, "sfig5_cohort_saturation")


# ── S-Fig 6a — Variance Violins (5A) ───────────────────────────────────────────

def build_sfig6a(fdir, out_dir):
    """S-Fig 6a — Within-Subject Variance Violins: sex, apnea, sleep_eff (1×3)."""
    print("Building S-Fig 6a — Variance Violins …")
    tasks  = ["sex_binary", "apnea_binary", "sleep_efficiency_binary"]
    sample = fdir / f"{tasks[0]}_transformer" / \
             f"{tasks[0]}_transformer_subject_consistency_5A_variance.png"
    fig, axes = make_grid(3, 3, fs(1, sample, 3))
    for i, (ax, task) in enumerate(zip(axes, tasks)):
        p = fdir / f"{task}_transformer" / \
            f"{task}_transformer_subject_consistency_5A_variance.png"
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, "sfig6a_variance_violins")


# ── S-Fig 6b — Hard-Subject Bars (5C) ──────────────────────────────────────────

def _build_sfig6b(tasks, fdir, out_dir, stem):
    n = len(tasks)
    n_cols = 3
    n_rows = (n + n_cols - 1) // n_cols
    sample = fdir / f"{tasks[0]}_transformer" / \
             f"{tasks[0]}_transformer_subject_consistency_5C_hard_subjects.png"
    fig, axes = make_grid_centered(n, n_cols, fs(n_rows, sample, n_cols))
    for i, (ax, task) in enumerate(zip(axes, tasks)):
        p = fdir / f"{task}_transformer" / \
            f"{task}_transformer_subject_consistency_5C_hard_subjects.png"
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, stem)

def build_sfig6b(fdir, out_dir):
    print("Building S-Fig 6b — Hard-Subject Bars, main tasks …")
    _build_sfig6b(MAIN_TASKS, fdir, out_dir, "sfig6b_hard_subjects_main")

def build_sfig6b_sec(fdir, out_dir):
    print("Building S-Fig 6b secondary — Hard-Subject Bars, secondary tasks …")
    _build_sfig6b(SECONDARY_TASKS, fdir, out_dir, "sfig6b_hard_subjects_secondary")


# ── S-Fig 7 — Window Position Profiles (4A, all main tasks) ───────────────────

def build_sfig7a(fdir, out_dir):
    """S-Fig 7a — Position profiles (4A) for all main tasks.
    4A PNGs are 2.63:1 (very wide), so n_cols=2 keeps panels at natural 1.33 in height.
    Layout: 3×2 (5 tasks, last row 1 panel centred)."""
    print("Building S-Fig 7a — Window Position Profiles (all main tasks) …")
    sample = fdir / f"{MAIN_TASKS[0]}_lstm" / \
             f"{MAIN_TASKS[0]}_lstm_window_position_4A_profiles.png"
    n_cols = 2
    n_rows = (len(MAIN_TASKS) + n_cols - 1) // n_cols
    fig, axes = make_grid_centered(len(MAIN_TASKS), n_cols, fs(n_rows, sample, n_cols))
    for i, (ax, task) in enumerate(zip(axes, MAIN_TASKS)):
        p = fdir / f"{task}_lstm" / f"{task}_lstm_window_position_4A_profiles.png"
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, "sfig7a_position_profiles")


def build_sfig7b(fdir, out_dir):
    """S-Fig 7b — Position variance (4B) for all main tasks.
    4B PNGs are 1.81:1; n_cols=2 gives ~1.93 in rows — well-proportioned.
    Layout: 3×2 (5 tasks, last row 1 panel centred)."""
    print("Building S-Fig 7b — Window Position Variance (all main tasks) …")
    sample = fdir / f"{MAIN_TASKS[0]}_lstm" / \
             f"{MAIN_TASKS[0]}_lstm_window_position_4B_variance.png"
    n_cols = 2
    n_rows = (len(MAIN_TASKS) + n_cols - 1) // n_cols
    fig, axes = make_grid_centered(len(MAIN_TASKS), n_cols, fs(n_rows, sample, n_cols))
    for i, (ax, task) in enumerate(zip(axes, MAIN_TASKS)):
        p = fdir / f"{task}_lstm" / f"{task}_lstm_window_position_4B_variance.png"
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, "sfig7b_position_variance")


# ── S-Fig 8 — Compute Scaling 1B ───────────────────────────────────────────────

def _build_sfig1(tasks, fdir, out_dir, stem):
    """S-Fig 1 — Compute Scaling 1B (first supplementary figure)."""
    n = len(tasks)
    n_cols = 3
    n_rows = (n + n_cols - 1) // n_cols
    sl     = fdir / "scaling_laws"
    sample = sl / f"{tasks[0]}_1B_compute_scaling.png"
    fig, axes = make_grid_centered(n, n_cols, fs(n_rows, sample, n_cols))
    for i, (ax, task) in enumerate(zip(axes, tasks)):
        p = sl / f"{task}_1B_compute_scaling.png"
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, stem)

def build_sfig1(fdir, out_dir):
    print("Building S-Fig 1 — Compute Scaling 1B, main tasks …")
    _build_sfig1(MAIN_TASKS, fdir, out_dir, "sfig1_compute_scaling_main")

def build_sfig1_sec(fdir, out_dir):
    print("Building S-Fig 1 secondary — Compute Scaling 1B, secondary tasks …")
    _build_sfig1(SECONDARY_TASKS, fdir, out_dir, "sfig1_compute_scaling_secondary")


# ── S-Fig 9 — PR Curves (renumbered: was S-Fig 10, kstar removed) ──────────────

def _build_pr(tasks, panel_fn, fdir, out_dir, stem):
    n = len(tasks)
    n_cols = 3
    n_rows = (n + n_cols - 1) // n_cols
    sample = panel_fn(fdir, tasks[0])
    fig, axes = make_grid_centered(n, n_cols, fs(n_rows, sample, n_cols))
    for i, (ax, task) in enumerate(zip(axes, tasks)):
        p = panel_fn(fdir, task)
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, stem)

def build_sfig9a(fdir, out_dir):
    """S-Fig 9a — PR Curves 8A (main binary tasks, Transformer)."""
    print("Building S-Fig 9a — PR Curves (main binary tasks) …")
    def path(fd, t):
        return fd / f"{t}_transformer" / f"{t}_transformer_pr_8A_curves.png"
    _build_pr(BINARY_MAIN, path, fdir, out_dir, "sfig9a_pr_curves_main")

def build_sfig9b(fdir, out_dir):
    """S-Fig 9b — AUC-PR vs Context 8B (main binary tasks, LSTM multi-head)."""
    print("Building S-Fig 9b — AUC-PR vs Context (main binary tasks) …")
    def path(fd, t):
        return fd / f"{t}_lstm" / f"{t}_pr_8B_aucpr_vs_context.png"
    _build_pr(BINARY_MAIN, path, fdir, out_dir, "sfig9b_aucpr_main")


# ── S-Fig 10 — U-Shape Training 1A (renumbered: was S-Fig 11) ──────────────────

def _build_sfig10(tasks, fdir, out_dir, stem):
    n = len(tasks)
    n_cols = 3
    n_rows = (n + n_cols - 1) // n_cols
    sl     = fdir / "scaling_laws"
    sample = sl / f"{tasks[0]}_transformer_1A_uShape.png"
    fig, axes = make_grid_centered(n, n_cols, fs(n_rows, sample, n_cols))
    for i, (ax, task) in enumerate(zip(axes, tasks)):
        p = sl / f"{task}_transformer_1A_uShape.png"
        show_img(ax, load_img(p), f"({chr(97+i)}) {TASK_SHORT[task]}")
    save_fig(fig, out_dir, stem)

def build_sfig10(fdir, out_dir):
    print("Building S-Fig 10 — U-Shape Training, main tasks …")
    _build_sfig10(MAIN_TASKS, fdir, out_dir, "sfig10_ushape_main")

def build_sfig10_sec(fdir, out_dir):
    print("Building S-Fig 10 secondary — U-Shape Training, secondary tasks …")
    _build_sfig10(SECONDARY_TASKS, fdir, out_dir, "sfig10_ushape_secondary")


# ── Dispatch ───────────────────────────────────────────────────────────────────

BUILDERS = {
    # Main figures
    "fig1":              build_fig1,
    "fig1_sec":          build_fig1_sec,
    "fig2_kvsk":         build_fig2_kvsk,
    "fig2_heatmap":      build_fig2_heatmap,
    "fig2_mincost":      build_fig2_mincost,
    "fig3":              build_fig3,
    # Iso-compute secondary tasks
    "sfig_iso_kvsk":     build_sfig_iso_kvsk_sec,
    "sfig_iso_heatmap":  build_sfig_iso_heatmap_sec,
    "sfig_iso_mincost":  build_sfig_iso_mincost_sec,
    # Supplementary figures (S-Fig 1 = compute scaling — first supp fig)
    "sfig1":             build_sfig1,      # S-Fig 1: Compute Scaling 1B
    "sfig1_sec":         build_sfig1_sec,
    "sfig2":             build_sfig2,      # S-Fig 2: K-Aggregation Curves
    "sfig2_sec":         build_sfig2_sec,
    "sfig3_main":        build_sfig3_main,
    "sfig3_marginal":    build_sfig3_marginal,
    "sfig4a":            build_sfig4a,
    "sfig4b":            build_sfig4b,
    "sfig5":             build_sfig5,
    "sfig6a":            build_sfig6a,
    "sfig6b":            build_sfig6b,
    "sfig6b_sec":        build_sfig6b_sec,
    "sfig7a":            build_sfig7a,
    "sfig7b":            build_sfig7b,
    # S-Fig 9 = PR curves (was 10; kstar removed)
    "sfig9a":            build_sfig9a,
    "sfig9b":            build_sfig9b,
    # S-Fig 10 = U-shape training (was 11)
    "sfig10":            build_sfig10,
    "sfig10_sec":        build_sfig10_sec,
    # S-Fig 11 = Aggregate scaling (pre-assembled, no builder needed here)
}


def main():
    parser = argparse.ArgumentParser(
        description="Assemble composite paper figures.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--fig",
                        choices=list(BUILDERS) + ["all"],
                        default="all",
                        help="Figure to build (default: all).")
    parser.add_argument("--figures-dir", required=True,
                        help="Path to phase0_v3 figures dir "
                             "(e.g. results/figures/phase0_v3).")
    parser.add_argument("--out-dir", default="results/figures/assembled",
                        help="Output directory (default: results/figures/assembled).")
    args = parser.parse_args()

    fdir    = Path(args.figures_dir)
    out_dir = Path(args.out_dir)

    if not fdir.exists():
        print(f"ERROR: --figures-dir does not exist: {fdir}", file=sys.stderr)
        sys.exit(1)

    targets = list(BUILDERS) if args.fig == "all" else [args.fig]
    for fid in targets:
        try:
            BUILDERS[fid](fdir, out_dir)
        except Exception as exc:
            print(f"  [ERROR] {fid}: {exc}", file=sys.stderr)
            import traceback; traceback.print_exc(file=sys.stderr)

    print(f"\nDone. Output: {out_dir}")


if __name__ == "__main__":
    main()
